export const GET_PRODUCTS = "GET_PRODUCTS"
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE'
export const GET_CATALOG = 'GET_CATALOG' 
export const GET_STYLE = 'GET_STYLE'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const RESET_MESS_ADD = 'RESET_MESS_ADD';
export const RESET_MESS_REMOVE = 'RESET_MESS_REMOVE'
export const RESET_ALL_ADD = 'RESET_ALL_ADD'

export const GET_POST = 'GET_POST';
export const ADD_POST = 'ADD_POST';
export const UPLOAD_IMAGE_POST = 'UPLOAD_IMAGE_POST'
export const RESET_MESS_ADD_POST = 'RESET_MESS_ADD_POST';
export const RESET_MESS_REMOVE_POST = 'RESET_MESS_REMOVE_POST'
export const RESET_ALL_ADD_POST = 'RESET_ALL_ADD_POST'
export const REMOVE_POST = 'REMOVE_POST'